   services:
     - type: web
       name: withham
       env: node
       buildCommand: npm install && npm run build && python manage.py migrate --noinput
       startCommand: npm start
       envVars:
         - key: NODE_ENV
           value: production
         - key: DB_NAME
           value: hunu_beta
         - key: DB_USER
           value: hunu_beta_user
         - key: DB_PASSWORD
           value: cIQZUqqwcTBCQwMS2b7YyKsKvntY9QIC
         - key: DB_HOST
           value: dpg-d087bhs9c44c73bk65o0-a.singapore-postgres.render.com
         - key: DB_PORT
           value: 5432