# Generated by Django 5.2 on 2025-04-11 07:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hamster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名前")),
                (
                    "breed",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="種類"
                    ),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="誕生日"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "男の子"), ("F", "女の子"), ("U", "不明")],
                        default="U",
                        max_length=1,
                        verbose_name="性別",
                    ),
                ),
                (
                    "profile_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="プロフィール"
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="hamster_images/",
                        verbose_name="プロフィール画像",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="登録日時"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hamsters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="飼い主",
                    ),
                ),
            ],
            options={
                "verbose_name": "ハムスター",
                "verbose_name_plural": "ハムスター",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="本文")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="post_images/",
                        verbose_name="画像",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="投稿日時"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="投稿者",
                    ),
                ),
                (
                    "hamster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="withham.hamster",
                        verbose_name="関連ハムスター",
                    ),
                ),
            ],
            options={
                "verbose_name": "投稿",
                "verbose_name_plural": "投稿",
                "ordering": ["-created_at"],
            },
        ),
    ]
