# Generated by Django 5.2 on 2025-04-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("withham", "0007_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="タグ名"),
                ),
            ],
            options={
                "verbose_name": "タグ",
                "verbose_name_plural": "タグ",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={},
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="withham.tag", verbose_name="タグ"
            ),
        ),
    ]
