# Generated by Django 5.2 on 2025-05-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("withham", "0008_tag_alter_userprofile_options_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_as_hamster",
            field=models.BooleanField(
                default=False, verbose_name="ハムスターとして投稿"
            ),
        ),
    ]
