# Generated by Django 5.2 on 2025-05-03 03:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("withham", "0009_post_post_as_hamster"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="質問タイトル"),
                ),
                ("text", models.TextField(verbose_name="質問内容")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="質問日時"
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="解決済み"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="質問者",
                    ),
                ),
            ],
            options={
                "verbose_name": "質問",
                "verbose_name_plural": "質問",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="回答内容")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="回答日時"
                    ),
                ),
                (
                    "is_best_answer",
                    models.BooleanField(default=False, verbose_name="ベストアンサー"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="回答者",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="withham.question",
                        verbose_name="対象質問",
                    ),
                ),
            ],
            options={
                "verbose_name": "回答",
                "verbose_name_plural": "回答",
                "ordering": ["created_at"],
            },
        ),
    ]
