# Generated by Django 5.2 on 2025-05-03 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("withham", "0010_question_answer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="author",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="author",
            new_name="user",
        ),
    ]
