# Generated by Django 5.2 on 2025-06-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("withham", "0011_rename_author_answer_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bookmarked_posts",
            field=models.ManyToManyField(
                blank=True, related_name="bookmarked_by", to="withham.post"
            ),
        ),
    ]
