# Generated by Django 5.2 on 2025-06-19 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("withham", "0012_userprofile_bookmarked_posts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="タイトル")),
                ("schedule_date", models.DateField(verbose_name="予定日")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HOSPITAL", "病院"),
                            ("CLEANING", "掃除"),
                            ("BIRTHDAY", "誕生日"),
                            ("OTHER", "その他"),
                        ],
                        default="OTHER",
                        max_length=10,
                        verbose_name="カテゴリ",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="メモ")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "hamster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="withham.hamster",
                        verbose_name="対象ハムスター",
                    ),
                ),
            ],
            options={
                "verbose_name": "予定",
                "verbose_name_plural": "予定",
                "ordering": ["schedule_date"],
            },
        ),
    ]
