# Generated by Django 5.2 on 2025-06-20 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("withham", "0013_schedule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={},
        ),
        migrations.RemoveField(
            model_name="post",
            name="post_as_hamster",
        ),
    ]
